CC=gcc
CFLAGS=-Wall

all: example1 example2 example3

example1: example1.c
	$(CC) $(CFLAGS) example1.c -o example1

example2: example2.c
	$(CC) $(CFLAGS) example2.c -o example2

example3: example3.c
	$(CC) $(CFLAGS) example3.c -o example3

clean:
	rm -f example1 example2 example3
