read_integers: read_integers.c
	gcc read_integers.c -o read_integers

read_and_find_a: read_and_find_a.c
	gcc read_and_find_a.c -o read_and_find_a

read_hello_world: read_hello_world.c
	gcc read_hello_world.c -o read_hello_world

clean:
	rm -f read_integers read_and_find_a read_hello_world